### ISSUE TITLE
Key error for recaptcha (Ajax validation)

### ISSUE THREAD

**Issue by microspace** [lepture/flask-wtf#189]
Almost same as #188 issue, except that I use ajax validation.
app.py:
```python
class SignUpForm(Form):
    phone = TextField('phone', [Required()])
    recaptcha = RecaptchaField()


@app.route('/')
def index():	
	return render_template("index.html", form = SignUpForm())

@app.route('/signUpUser', methods = ['GET', 'POST'])
def login():
    if request.method == 'POST':
        form = SignUpForm(request.form)
        if form.validate():
            result = {}
            result['iserror'] = False
            #print (form.phone.data)
            record = Record (phone=form.phone.data)
            db.session.add(record)
            db.session.commit()
            return json.dumps(result)

        form.errors['iserror'] = True
        return json.dumps(form.errors)
```
index.html
```html
            {% block content %}
            <form role="form" method="post" id="signupform">
                {{form.hidden_tag()}}
                <div class="form-group">
                <p>
                    {{form.phone(size=80)}}<br>
                    {{ form.recaptcha }}
                </p>
                <p id="error_title"></p>
                </div>
                <button type="button" type="submit" class="btn btn-default" id="signup">Отправить</button>
            </form>
            {% endblock %}
```

```javascript
$("#signup").click(function(){
        $.post(  
            "/signUpUser",  
            $("#signupform").serialize(),  
            function(data, textStatus) {
              var errors = $.parseJSON(data);
                $("#error_title").text("");
                $("#error_description").text("");
                $("#error_tags").text("");
                
                if(errors.iserror)
                {       
                	
                    if(errors.phone!=undefined) $("#signuptext").text("no tel number!");

                } else 
                {
                    $("#signupform").css("display","none");
                }
            }  
        );
    });
```
Everything is ok when I pass form validation.
Problem occurs when I don't pass form validation, but pass recaptcha validation.
I get this error listing:
```
2015-07-08 19:02:28 [13879] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/www/flask_project/app.py", line 51, in login
    if form.validate():
  File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/usr/local/lib/python2.7/dist-packages/wtforms/fields/core.py", line 200, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/fields/core.py", line 220, in _run_validation_chain
    validator(form, self)
  File "/usr/local/lib/python2.7/dist-packages/flask_wtf/recaptcha/validators.py", line 47, in __call__
    if not self._validate_recaptcha(response, remote_ip):
  File "/usr/local/lib/python2.7/dist-packages/flask_wtf/recaptcha/validators.py", line 74, in _validate_recaptcha
    for error in json_resp["error-codes"]:
KeyError: 'error-codes
```

**Comment by microspace** [comment]
Maybe problem is that there is a spetial js file for recaptcha ajax validation as mentioned is https://github.com/praekelt/django-recaptcha project.

>AJAX

>To make Recapcha work in ajax-loaded forms:

>import recaptcha_ajax.js on your page (not in the loaded template):

><script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>
>settings.py

>CAPTCHA_AJAX = True
>

**Comment by lepture** [comment]
I've released a new version. Try the new one.

**Comment by microspace** [comment]
Problem is gone! Thank you very much!
