### ISSUE TITLE
error when changing from version0.13.1 to 0.14

### ISSUE THREAD

**Issue by abc19899** [lepture/flask-wtf#275]
~~~python-traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./tencent_web_charge/single_server_query/views.py", line 69, in choose_platform
    form = ChoosePlatformForm()
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/usr/local/lib/python3.6/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/usr/local/lib/python3.6/site-packages/flask_wtf/csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/usr/local/lib/python3.6/site-packages/flask_wtf/csrf.py", line 47, in generate_csrf
    setattr(g, field_name, s.dumps(session[field_name]))
  File "/usr/local/lib/python3.6/site-packages/itsdangerous.py", line 565, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "/usr/local/lib/python3.6/site-packages/itsdangerous.py", line 847, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "/usr/local/lib/python3.6/site-packages/itsdangerous.py", line 550, in dump_payload
    return want_bytes(self.serializer.dumps(obj))
  File "/usr/local/lib/python3.6/site-packages/itsdangerous.py", line 51, in dumps
    return json.dumps(obj, separators=(',', ':'))
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
~~~

~~~python
class ChoosePlatformForm(flask_wtf.FlaskForm):
    platform = wtforms.SelectField(
        '平台', validators=[wtforms.validators.DataRequired()],
        choices=[
            ('android', '安卓混服'),
            ('tencent', '腾讯应用宝'),
            ('app', '苹果官方'),
            ('xingyun', '独服'),
            ('test', '测试')
        ]
    )
    submit = wtforms.SubmitField(
        '确定',
    )

@delayed_route('/choose_platform', methods=['GET', 'POST'])
def choose_platform():
    form = ChoosePlatformForm()
    if form.validate_on_submit():
        response = make_response(redirect(url_for('.choose_server', next=request.args.get('next', None))))
        response.set_cookie('platform', form.platform.data)
        return response

    return render_template('simple_form.html', form=form)
~~~

I am using Python 3.

**Comment by davidism** [comment]
I can't reproduce your issue. The session token is generated as a string, not bytes, on Python 3, and the serializer handles is correctly.

The only thing I can think of is that there might be invalid data in the session due to the change in how the token is generated, but I couldn't reproduce that either. Try clearing the browser's cookies for your app (probably localhost or 127.0.0.1).

If that doesn't work, you'll need to provide a self-contained example that reproduces the issue.

**Comment by guillaumep** [comment]
This has happened to me when upgrading my code from Python 2 to Python 3. The browser had cookies set by Python 2 code. Python 3 interpreted the cookie content as byte strings.

Deleting the cookie solved the issue.

**Comment by ojosdegris** [comment]
@guillaumep OMG it really was cookies. I was so confused while everything was working fine locally but was broken inside docker container and it was just cookies.

**Comment by aleonchen** [comment]
@ojosdegris Yes, same to me. It took me hours to fix it.

**Comment by javaor** [comment]
@guillaumep  really thanks

**Comment by janwilamowski** [comment]
as a workaround, you could try running
```
if type(session['csrf_token']) is bytes:
    del session['csrf_token']
```
before instantiating the form. This should remove the leftover (Python 2) CSRF token and trigger recreating it.
