### ISSUE TITLE
TypeError: b'' is not JSON serializable

### ISSUE THREAD

**Issue by yerassyl** [lepture/flask-wtf#279]
While using python 3.5.2 I got this error: TypeError: b'' is not JSON serializable
So there is a problem with serializing a byte string
For me I solved it this way editing csrf.py generate_csrf method:
        setattr(g, field_name, s.dumps(session[field_name].decode('utf-8')))
I added .decode('utf-8') to session[field_name] to make it work on python 3.

I am not sure if this is an issue, but may be I helped somehow :)

**Comment by lepture** [comment]
Tested on python 3.5 and 3.6, cannot reproduce.

**Comment by davidism** [comment]
Duplicate of #275. As stated there, you'll need to provide a self-contained example that reproduces the issue.

**Comment by zgoda** [comment]
Just been bitten by this:

```
Traceback (most recent call last):
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jazg/work/emucompat/ecpapp/report/views.py", line 28, in details
    form = GameReportForm()
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/flask_wtf/form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/flask_wtf/csrf.py", line 134, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/flask_wtf/csrf.py", line 47, in generate_csrf
    setattr(g, field_name, s.dumps(session[field_name]))
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/itsdangerous.py", line 565, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/itsdangerous.py", line 847, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/itsdangerous.py", line 550, in dump_payload
    return want_bytes(self.serializer.dumps(obj))
  File "/home/jazg/v/emcp/lib/python3.5/site-packages/itsdangerous.py", line 51, in dumps
    return json.dumps(obj, separators=(',', ':'))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'3fd29c1aa98364b053ef0c6bd53479276d6956e4' is not JSON serializable
```

**Comment by zgoda** [comment]
This goes away after clearing browser cookies. I suppose I had a dangling session from one site running on Python 2.7.

**Comment by datashaman** [comment]
Asking customers to clear session cookies is not a viable option. I will submit a PR.

**Comment by datashaman** [comment]
NM, it seems master has solved this problem. I'll see what I can do about switching to the master branch instead.

**Comment by olivejt** [comment]
@zgoda It works!

**Comment by avilaton** [comment]
Hi @davidism ,
what are the chances we get a new release?
Thanks

**Comment by guomaoqiu** [comment]
* Python3.5
* I'm use flask  itsdangerous TimedJSONWebSignatureSerializer generate access_token:

![image](https://user-images.githubusercontent.com/9714859/44319893-4a52cc00-a471-11e8-98af-0315a22d4522.png)


Error is:
![image](https://user-images.githubusercontent.com/9714859/44319801-a9641100-a470-11e8-9a89-ed8e8f5c36d1.png)

help me ,please.
