### ISSUE TITLE
ERROR in views: The referrer header is missing.

### ISSUE THREAD

**Issue by rlam3** [lepture/flask-wtf#288]
I'm trying to use CSRFToken with SSL. I'm getting the following error

```python
ERROR in views: The referrer header is missing.
```

The following is my nginx config file 

```nginx
# Http will always redirect me back to https
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # Redirect all HTTP requests to HTTPS with a 301 Moved Permanently response.
    rewrite ^(.*) https://$host$request_uri;
}

# HTTPS server
server {

  listen 443 ssl;
  listen [::]:443;
  server_name alpha.example.com example.com;

  root /home/XXX/www/example_app/example_app;

  access_log /var/log/nginx/exampele.com.access.log combined;
  error_log /var/log/nginx/exampele.com.error.log error;

  ssl on;
  ssl_certificate /etc/nginx/ssl/example.com/cert.pem;
  ssl_certificate_key /etc/nginx/ssl/example.com/key.pem;

  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:50m;

  ssl_protocols TLSv1.2;
  ssl_ciphers EECDH+AESGCM:EECDH+AES;
  ssl_ecdh_curve secp384r1;
  ssl_prefer_server_ciphers on;

  ssl_stapling on;
  ssl_stapling_verify on;

  add_header Strict-Transport-Security "max-age=15768000; includeSubdomains; preload";
  add_header X-Frame-Options DENY;
  add_header X-Content-Type-Options nosniff;


  location /robots.txt {
    alias /home/XXX/www/example_app/example_app/static/build/robots.txt;
    expires 30d;
    add_header Cache-Control "public";
  }

  proxy_buffer_size 128k;
  proxy_buffers 4 256k;
  proxy_busy_buffers_size 256k;

  charset utf-8;
  client_max_body_size 75M;

  location / {

      proxy_pass_header X-CSRFToken;

      include uwsgi_params;
      uwsgi_pass unix:///tmp/example_app.sock;

  }

  # serve static files - each entry is a separate folder
  location ~ ^/(img|js|css)/  {
    # Directly assigning to built assets instead of alias
    root /home/XXX/www/example_app/example_app/static/build;
    autoindex on;
    add_header Cache-Control "public";
    expires 30d;
  }

}
```

The traceback:

```
[2017-03-31 13:53:06,205] ERROR in views: The referrer header is missing.
Traceback (most recent call last):
  File "/home/XXX/www/env/local/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/XXX/www/env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/home/XXX/www/env/local/lib/python2.7/site-packages/flask_wtf/csrf.py", line 221, in csrf_protect
    self.protect()
  File "/home/XXX/www/env/local/lib/python2.7/site-packages/flask_wtf/csrf.py", line 256, in protect
    self._error_response('The referrer header is missing.')
  File "/home/XXX/www/env/local/lib/python2.7/site-packages/flask_wtf/csrf.py", line 324, in handler
    response = current_app.make_response(view(reason))
  File "./example/error_handler/views.py", line 126, in csrf_error
    raise InvalidAPIUsage(message=error, status_code=400)
InvalidAPIUsage

```

When I am not using https/ssl this error does not occur. I'm assuming there is some sort of proxy that I have to enable for my other headers such as Authorization, etc. my API to work? Would love to hear what feedback there is to this strange issue with SSL.

Thanks!

**Comment by rlam3** [comment]
I see that my issue is related to http://flask-wtf.readthedocs.io/en/stable/config.html?highlight=referrer

And I can probably turn this off if I wanted. But I'd really like to know:

1. There is something I can set through nginx as a work around. 
2. What is the reason behind WTF_CSRF_SSL_STRICT ? Why do we need that?
