### ISSUE TITLE
Length validator crash when post wrong data type.

### ISSUE THREAD

**Issue by nnnewb** [lepture/flask-wtf#295]
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
""" test given invalid data type
"""

from flask import Flask
from flask_wtf import FlaskForm
from wtforms.validators import Length
from wtforms import StringField


class TestForm(FlaskForm):
    """ try this form
    """
    test = StringField(
        'test',
        validators=[
            Length(2, 32, 'this message never show')
        ]
    )

app = Flask('app')


@app.route('/test', methods=['POST'])
def test_view():
    form = TestForm()
    if form.validate_on_submit():
        return 'good'
    return 'opps'


if __name__ == '__main__':
    app.config['SECRET_KEY'] = 'secret'
    app.run(port=4321)
```

test code
```bash
curl -l -H 'Content-Type: application/json' -X POST -d '{"test": 0.1}' 'http://localhost:4321/
```
and crash log here
```
[2017-06-06 10:28:26,335] ERROR in app: Exception on /test [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/______/github/test/server.py", line 28, in test_view
    if form.validate_on_submit():
  File "/usr/local/lib/python2.7/dist-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/usr/local/lib/python2.7/dist-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/validators.py", line 92, in __call__
    l = field.data and len(field.data) or 0
TypeError: object of type 'float' has no len()
```

**Comment by lepture** [comment]
It should be reported to wtforms.

**Comment by nnnewb** [comment]
thanks, my fault.
