### ISSUE TITLE
cannot import name 'FlaskForm'

### ISSUE THREAD

**Issue by Toxenum** [lepture/flask-wtf#345]
When I run
`from flask_wtf import FlaskForm`

I get:

```pytb
Traceback (most recent call last):
  File "F:/Dokumente/Programmierung/Python/wtforms/wtforms.py", line 5, in <module>
    from flask_wtf import FlaskForm
  File "C:\Users\Niklas\Documents\venvs\testenv\lib\site-packages\flask_wtf\__init__.py", line 15, in <module>
    from .csrf import CSRFProtect, CsrfProtect
  File "C:\Users\Niklas\Documents\venvs\testenv\lib\site-packages\flask_wtf\csrf.py", line 11, in <module>
    from wtforms import ValidationError
  File "F:\Dokumente\Programmierung\Python\wtforms\wtforms.py", line 5, in <module>
    from flask_wtf import FlaskForm
ImportError: cannot import name 'FlaskForm'`
```

The versions I use are:
Flask-WTF 2.2.1
Flask 1.0.2
Python 3.6.5

**Comment by davidism** [comment]
Name your top-level module something besides "wtforms.py", it's shadowing the real wtforms name and causing a circular import.

**Comment by Toxenum** [comment]
Thank you :)

**Comment by Kartz1986** [comment]
Thanks a lot. The error was confusing for a quite a long time ..now i understand my error.
