### ISSUE TITLE
no module named 'wtforms.csrf' after pip install flask-wtf

### ISSUE THREAD

**Issue by my-name-is-njuno** [lepture/flask-wtf#351]
After installing flask-wtf with pip and running app.py , below is the error

PS D:\python\sublime\flaskdbapp> python app.py
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from forms import Registration, Login
  File "D:\python\sublime\flaskdbapp\forms.py", line 1, in <module>
    from flask_wtf import FlaskForm
  File "C:\Users\laravel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_wtf-0.14.2-py3.7.egg\flask_wtf\__init__.py", line 15, in <module>
    from .csrf import CSRFProtect, CsrfProtect
  File "C:\Users\laravel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_wtf-0.14.2-py3.7.egg\flask_wtf\csrf.py", line 12, in <module>
    from wtforms.csrf.core import CSRF
ModuleNotFoundError: No module named 'wtforms.csrf'

Have installed and tried with easy install and same error, have searched everywhere no clue what wrong, kindly assist

**Comment by davidism** [comment]
I can't reproduce this error. It's odd that `pip install` produced `.egg` files in `site-packages`, but that shouldn't cause this. My only guess would be that you have a file called "wtforms.py" in your own code.
