### ISSUE TITLE
Fails on label attribute

### ISSUE THREAD

**Issue by kontur** [lepture/flask-wtf#372]
Hey,

I'm pretty certain I am overseeing something totally basic, but when I expand the basic quickstart example simply by adding a `label="…"` definition I get this error:

```
Traceback (most recent call last):
  File "…app/venv/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "…app/venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "…app/venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "…app/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "…app/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "…app/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "…app/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "…app/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "…app/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "…app/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "…app/app.py", line 87, in cart
    form = CartForm()
  File "…app/venv/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "…app/venv/lib/python3.7/site-packages/flask_wtf/form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "…app/venv/lib/python3.7/site-packages/wtforms/form.py", line 272, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "…app/venv/lib/python3.7/site-packages/wtforms/form.py", line 52, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "…app/venv/lib/python3.7/site-packages/wtforms/meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "…app/venv/lib/python3.7/site-packages/wtforms/fields/core.py", line 353, in bind
    return self.field_class(*self.args, **kw)
TypeError: __init__() got multiple values for argument 'label'
```

So this works:
```
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired

class CartForm(FlaskForm):
    name = StringField('name', validators=[DataRequired()])
```

But this fails, with the error triggered on the line where I instantiate my form:
```
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired

class CartForm(FlaskForm):
    name = StringField('name', label="Your name", validators=[DataRequired()])
```

I'm using Python 3.7.3 and:
Flask                  1.1.0
Flask-WTF         0.14.2
WTForms           2.2.1

**Comment by kontur** [comment]
Equally adding a `choices` attributes to a `SelectField` also breaks the form instantiation:

```
TypeError: __init__() got an unexpected keyword argument 'choices'
```

**Comment by dodumosu** [comment]
> So this works:
> 
> ```
> from flask_wtf import FlaskForm
> from wtforms import StringField
> from wtforms.validators import DataRequired
> 
> class CartForm(FlaskForm):
>     name = StringField('name', validators=[DataRequired()])
> ```
That's because the first argument is the label.
> But this fails, with the error triggered on the line where I instantiate my form:
> 
> ```
> from flask_wtf import FlaskForm
> from wtforms import StringField
> from wtforms.validators import DataRequired
> 
> class CartForm(FlaskForm):
>     name = StringField('name', label="Your name", validators=[DataRequired()])
> ```
That's because you specified the `label` argument twice: once by position, and once by keyword.
