### ISSUE TITLE
Import Error with new Werkzeug update

### ISSUE THREAD

**Issue by RafaelCenzano** [lepture/flask-wtf#394]
ImportError: cannot import name 'url_encode' from 'werkzeug'

Imports listed while trying to import my form.py

`    from flask_wtf import FlaskForm
venv/lib/python3.8/site-packages/flask_wtf/__init__.py:17: in <module>
    from .recaptcha import *
venv/lib/python3.8/site-packages/flask_wtf/recaptcha/__init__.py:2: in <module>
    from .fields import *
venv/lib/python3.8/site-packages/flask_wtf/recaptcha/fields.py:3: in <module>
    from . import widgets
venv/lib/python3.8/site-packages/flask_wtf/recaptcha/widgets.py:5: in <module>
    from werkzeug import url_encode`

This only occurs using werkzeug's new version 1.0.0

**Comment by mgasner** [comment]
this is resolved in https://github.com/lepture/flask-wtf/pull/378

**Comment by mgasner** [comment]
would be great for downstream (incl. Apache Airflow) if flask-wtf could run a patch release including that PR

**Comment by karnaker** [comment]
I am seeing a similar error
flask-wtf 0.14.2
werkzeug 1.0.0
Hope traceback below is helpful

Traceback (most recent call last):
  File "C:\Users\vkarn\OneDrive\repos6\mvp1wk_web\thewebsite.py", line 4, in <module>
    app = create_app()
  File "C:\Users\vkarn\OneDrive\repos6\mvp1wk_web\app\__init__.py", line 40, in create_app
    from app.auth import bp as auth_bp
  File "C:\Users\vkarn\OneDrive\repos6\mvp1wk_web\app\auth\__init__.py", line 5, in <module>
    from app.auth import routes
  File "C:\Users\vkarn\OneDrive\repos6\mvp1wk_web\app\auth\routes.py", line 8, in <module>
    from app.auth.forms import (LoginForm, SignUpForm, ResetPasswordRequestForm,
  File "C:\Users\vkarn\OneDrive\repos6\mvp1wk_web\app\auth\forms.py", line 1, in <module>
    from flask_wtf import FlaskForm
  File "C:\Users\vkarn\.conda\envs\mvp_web_5\Lib\site-packages\flask_wtf\__init__.py", line 17, in <module>
    from .recaptcha import *
  File "C:\Users\vkarn\.conda\envs\mvp_web_5\Lib\site-packages\flask_wtf\recaptcha\__init__.py", line 2, in <module>
    from .fields import *
  File "C:\Users\vkarn\.conda\envs\mvp_web_5\Lib\site-packages\flask_wtf\recaptcha\fields.py", line 3, in <module>
    from . import widgets
  File "C:\Users\vkarn\.conda\envs\mvp_web_5\Lib\site-packages\flask_wtf\recaptcha\widgets.py", line 5, in <module>
    from werkzeug import url_encode
ImportError: cannot import name 'url_encode' from 'werkzeug' (c:\users\vkarn\.conda\envs\mvp_web_5\lib\site-packages\werkzeug\__init__.py)

**Comment by davidism** [comment]
Currently working on making a release.

**Comment by davidism** [comment]
Version 0.14.3 is available on PyPI.
