### ISSUE TITLE
TypeError raised when loading form with hidden_tag() on Flask 2.0.0rc1 (pre release)

### ISSUE THREAD

**Issue by jtrip** [lepture/flask-wtf#433]
# Requirements
```
click==8.0.0rc1
Flask==2.0.0rc1
Flask-WTF==0.14.3
itsdangerous==2.0.0rc2
Jinja2==3.0.0rc1
MarkupSafe==2.0.0rc2
Werkzeug==2.0.0rc4
WTForms==2.3.3
```

# Example
```
import os
from flask import Flask, render_template_string
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired
from flask_wtf.csrf import CSRFProtect


class MyForm(FlaskForm):
    name = StringField('name', validators=[DataRequired()])


app = Flask(__name__)
app.config['SECRET_KEY'] = os.urandom(24).hex()
csrf = CSRFProtect(app)


@app.route('/')
def hello_world():
    form = MyForm()
    return render_template_string('''
    <form method="POST" action="/">
        {{ form.hidden_tag() }}
        {{ form.name.label }} {{ form.name(size=20) }}
        <input type="submit" value="Go">
    </form>
    ''', form=form)


if __name__ == '__main__':
    app.run()

```

# Traceback
```
Traceback (most recent call last):
  File "/.../pre-venv/lib/python3.9/site-packages/flask/app.py", line 1971, in __call__
    return self.wsgi_app(environ, start_response)
  File "/.../pre-venv/lib/python3.9/site-packages/flask/app.py", line 1956, in wsgi_app
    response = self.handle_exception(e)
  File "/.../pre-venv/lib/python3.9/site-packages/flask/app.py", line 1953, in wsgi_app
    response = self.full_dispatch_request()
  File "/.../pre-venv/lib/python3.9/site-packages/flask/app.py", line 1454, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/.../pre-venv/lib/python3.9/site-packages/flask/app.py", line 1452, in full_dispatch_request
    rv = self.dispatch_request()
  File "/.../pre-venv/lib/python3.9/site-packages/flask/app.py", line 1438, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/.../app.py", line 21, in hello_world
    return render_template_string('''
  File "/.../pre-venv/lib/python3.9/site-packages/flask/templating.py", line 145, in render_template_string
    return _render(ctx.app.jinja_env.from_string(source), context, ctx.app)
  File "/.../pre-venv/lib/python3.9/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/.../pre-venv/lib/python3.9/site-packages/jinja2/environment.py", line 1127, in render
    self.environment.handle_exception()
  File "/.../pre-venv/lib/python3.9/site-packages/jinja2/environment.py", line 814, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 3, in top-level template code
    
  File "/.../pre-venv/lib/python3.9/site-packages/flask_wtf/form.py", line 133, in hidden_tag
    return Markup(
  File "/.../pre-venv/lib/python3.9/site-packages/jinja2/utils.py", line 843, in __init__
    super().__init__(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

# Notes
Using  `form.csrf_token` in the place of `hidden_tag()` in the template raises no exception.

Also my assumption is that `hidden_tag()` does not require the existence of additional hidden form elements as I believe this works as expected on Flask 1.1.2.

Thank you for the consideration in preparation for Flask 2.0

**Comment by davidism** [comment]
Fixed in Jinja master.

**Comment by davidism** [comment]
`pip install --pre -U jinja2` to get Jinja 3.0.0rc2.
